### ISSUE TITLE
Workflow crashes when hi-c read input uses dash before read2

### ISSUE THREAD

**Issue by mahesh-panchal** [NBISweden/Earth-Biogenome-Project-pilot#141]
The assembly parameters input file should be formatted like:
```yml
hic:
  - read1: '/path/to/data'
    read2: '/path/to/data'
```
but when a user formats the yml like:
```yml
hic:
  - read1: '/path/to/data'
  - read2: '/path/to/data'
```
Then the workflow complains about a `null` input to read2. 

There is a bash snippet to auto-generate the yml input written into the assembly_parameters.yml, but this can easily be missed.
