### ISSUE TITLE
MERYL_COUNT fails on run with steps: 'screen,scaffold,curate'

### ISSUE THREAD

**Issue by gbdias** [NBISweden/Earth-Biogenome-Project-pilot#232]
**Describe the bug**
I tried running the pipeline where I provided a purged assembly and specify the steps 'screen,scaffold,curate' in the `workflow_parameters.yml`. It completes scaffolding successfully, but screening fails with an error on the MERYL_COUNT process, and curation doesn't start because of that.

**To Reproduce**
workflow_parameters.yml
```
project: 'uppmax2025-2-58'
input: 'assembly_parameters.yml'
mitohifi:
  code: 5 # TODO; Select genetic code (-o) https://github.com/marcelauliano/MitoHiFi?tab=readme-ov-file#3-parameter-list
steps: 'screen,scaffold,curate'
```
assembly_parameters.yml
```
# Mandatory - sample metadata
sample:
  name: 'Dicellophilus carniolensis'

# Optional - HiFi data if available
hifi:
  - reads: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/PacBio-WGS/m84045_240531_164906_s1.hifi_reads.bc2040.bam'

# Optional - Hi-C data if available
hic:
  - read1: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/Illumina-HIC/sample_TAGACCAA+TCACCTTG_part1_R1.fastq.gz'
    read2: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/Illumina-HIC/sample_TAGACCAA+TCACCTTG_part1_R2.fastq.gz'
  - read1: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/Illumina-HIC/sample_TAGACCAA+TCACCTTG_part2_R1.fastq.gz'
    read2: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/Illumina-HIC/sample_TAGACCAA+TCACCTTG_part2_R2.fastq.gz'
  - read1: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/Illumina-HIC/sample_TAGACCAA+TCACCTTG_part3_R1.fastq.gz'
    read2: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/Illumina-HIC/sample_TAGACCAA+TCACCTTG_part3_R2.fastq.gz'
  - read1: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/Illumina-HIC/sample_TAGACCAA+TCACCTTG_part4_R1.fastq.gz'
    read2: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/Illumina-HIC/sample_TAGACCAA+TCACCTTG_part4_R2.fastq.gz'
  - read1: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/Illumina-HIC/YB-4221-HC012-2A1A_S151_L008_R1_001.fastq.gz'
    read2: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/raw-data/Illumina-HIC/YB-4221-HC012-2A1A_S151_L008_R2_001.fastq.gz'

# Optional - frozen/finalized assemblies
assembly:
  - assembler: 'hifiasm'
    stage: 'purged'
    id: 'dcar_purged'
    pri_fasta: '/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/data/outputs/01_asm_hic/05_duplicate_purging/purge_dups/dcar_purged_rescued.fa'
```
nextflow.config
```
// Add custom module configuration here

// E.g Use high memory node for HIFIASM
//process {
//    withName: 'HIFIASM' {
//        ext.args = { "--telo-m TAACC -l3" }
//    }
//}

process {
    withName: 'MERYL_COUNT' {
        cpus = 20
        memory     = 1024.GB
        time       = 2.d
        clusterOptions = { "-A $params.project -p node -C mem1TB" }
    }
}

process {
    withName: 'SCAFFOLD_CURATION:BAM2BED_SORT' {
        memory = 150.GB
    }
}
```

**The error**

.nextflow.log

```
ERROR ~ Cannot get property 'name' on null object

 -- Check script '/home/guibo205/git/NBIS/Earth-Biogenome-Project-pilot/modules/local/functions.nf' at line: 149 or see '.nextflow.log' file for more details

            Thank you for using the NBIS Earth Biogenome Project Assembly workflow.
            The workflow completed unsuccessfully.

            Please read over the error message. If you are unable to solve it, please
            post an issue at https://github.com/NBISweden/Earth-Biogenome-Project-pilot/issues
            where we will do our best to help.

WARN: Killing running tasks (3)
```

.command.sh
```
#!/usr/bin/env bash -C -e -u -o pipefail
for READ in sample_TAGACCAA+TCACCTTG_part4_R_1.fastp.fastq.gz sample_TAGACCAA+TCACCTTG_part4_R_2.fastp.fastq.gz; do
    meryl count \
        k=31 \
        threads=16 \
        memory=112 \
         \
        $READ \
        output read.${READ%.f*}.meryl
done

cat <<-END_VERSIONS > versions.yml
"BUILD_MERYL_HIC_DATABASE:MERYL_COUNT":
    meryl: $( meryl --version |& sed 's/meryl //' )
END_VERSIONS
```

tail .command.log
```
Used 43.203 GB / 111.875 GB to store   7576007978 kmers; need 8.533 GB to sort     35790419 kmers
Used 43.311 GB / 111.875 GB to store   7597075591 kmers; need 8.556 GB to sort     35886227 kmers
Used 43.411 GB / 111.875 GB to store   7616764030 kmers; need 8.581 GB to sort     35990943 kmers
Used 43.520 GB / 111.875 GB to store   7638037775 kmers; need 8.606 GB to sort     36094220 kmers

Input complete.  Writing results to 'read.sample_TAGACCAA+TCACCTTG_part4_R_2.fastp.meryl', using 16 threads.
slurmstepd: error: *** JOB 56035262 ON r335 CANCELLED AT 2025-06-25T18:29:04 ***
rm: cannot remove '/scratch/56035262/nxf.7Wu8roiHm2': Device or resource busy
```

**Note**
MERYL ran successfully on this dataset before with the same pipeline version, on a run with the full pipeline.
`/proj/snic2021-6-194/BGE-Dicellophilus_carniolensis-2024-assembly/analyses/01_asm_hic`
