### ISSUE TITLE
Question: How to run EVALUATE_ASSEMBLY process without the 'assemble' step

### ISSUE THREAD

**Issue by gbdias** [NBISweden/Earth-Biogenome-Project-pilot#70]
Now that the assembly evaluation is included in the 'assemble' workflow step, how do I evaluate an assembly produced outside of the pipeline?

I can skip assembly by using the steps parameter:
```
params {
    steps              = 'inspect,preprocess,screen'
}
```
But that skips evaluation as well.

**Comment by mahesh-panchal** [comment]
So as of commit https://github.com/NBISweden/Earth-Biogenome-Project-pilot/commit/5b9171f2df3cf7cc9c810c6ad691b79f88ff72c0 there's a few steps at the moment to make it work.

- You need to include `stage: raw` in the assembly input because of L125 in main.nf.
- You need to disable HIFIASM using a custom config so the workflow doesn't run on the assembler on the reads. 

Your input file should look like:
```yaml
sample:
  name: Species name
assembly:
  - assembler: hifiasm
    stage: raw
    id: uuid
    pri_fasta: /path/to/primary_asm.fasta
    alt_fasta: /path/to/alternate_asm.fasta
    pri_gfa: /path/to/primary_asm.gfa
    alt_gfa: /path/to/alternate_asm.gfa
  - assembler: ipa
    stage: raw
    id: uuid
    pri_fasta: /path/to/primary_asm.fasta
    alt_fasta: /path/to/alternate_asm.fasta
hifi:
  - reads: /path/to/reads
```
where uuid is some unique ID. 
and your custom config should look like:
```nextflow
process {
    withName: 'HIFIASM' {
        ext.when = false
    }
}
```
Do the same for `MITOHIFI_FINDMITOREFERENCE` too if you don't want that to run either. 
That should run only the evaluation tools then during the assemble stage. 

Note this is just a fix and I'll make proper support once I'm back from holiday.
